name: Deploy to Production

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build Project
              run: npm run build

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.PRODUCTION_HOST }}
                username: ${{ secrets.PRODUCTION_USERNAME }}
                key: ${{ secrets.PRODUCTION_SSH_KEY }}
                script: |
                  cd /path/to/production
                  git fetch
                  git checkout ${{ github.ref_name }}
                  npm ci --production
                  pm2 restart ecosystem.config.js

