name: Deploy to Staging

on:
    push:
        branches: [ main ]
            
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
                cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.STAGING_HOST }}
                username: ${{ secrets.STAGING_USERNAME }}
                key: ${{ secrets.STAGING_SSH_KEY }}
                script: |
                  cd /path/to/staging
                  git pull origin main
                  npm ci --production
                  pm2 restart ecosystem.config.js